### ISSUE TITLE
Fallbacks for empty dictionary phrases

### ISSUE THREAD

**Issue by Bagnall** [taoensso/tempura#7] opened 2017-02-08 14:00 UTC
Hi Peter,

I have a dictionary with
`:en-US {:missing "Missing text for en-US"}`
and
`:en-GB {:missing                      "Missing text for en-GB"
           :error-message-dialog         {:header .....`

I wanted missing translations for en-US to default to those in en-GB, by specifying the "Vector of descending-preference locales to search" to be `[:en-US :en-GB]`, however I'm seeing just "Missing text for en-US" everywhere. Do I have to duplicate every phrase from en-GB to en-US, rather than just define en-US phrases that differ from en-GB phrases?

Thanks in advance.

**Comment by robjinman** [comment] 2017-02-10 11:18
This seems to only happen when the locale names contain a hyphen and are identical before the hyphen.

```
(taoensso.tempura/tr {:dict {:en1 {:missing "missing"
                                   :page-1 {:a "hello"
                                            :b "goodbye"}}
                             :en2 {:missing "oh no"
                                   :page-1 {:a "bonjour"}}}}
                     [:en2 :en1] [:page-1/b])
```

As :page-1/b is absent from en2, the value "goodbye" is retrieved from en1 as expected.

When the locales are renamed:

```
(taoensso.tempura/tr {:dict {:en-1 {:missing "missing"
                                    :page-1 {:a "hello"
                                             :b "goodbye"}}
                             :en-2 {:missing "oh no"
                                    :page-1 {:a "bonjour"}}}}
                     [:en-2 :en-1] [:page-1/b])
```

This returns "oh no", when it should return "goodbye" as before.

Hyphenated locales work okay when the part before the hyphen is different:

```
(taoensso.tempura/tr {:dict {:en-1 {:missing "missing"
                                    :page-1 {:a "hello"
                                             :b "goodbye"}}
                             :fr-2 {:missing "oh no"
                                    :page-1 {:a "bonjour"}}}}
                     [:fr-2 :en-1] [:page-1/b])
```

This returns "goodbye" as expected.

**Comment by ptaoussanis** [comment] 2017-02-13 20:39
Hey Richard, this looks like a bug - thanks for the report. And thanks for the extra info Rob, that was helpful in pinning down the exact cause quickly!

Will get this resolved with the next Tempura update.

**Comment by ptaoussanis** [comment] 2017-02-16 18:08
Hey there!

So looked at this more closely and seems this isn't actually a bug, but intended (though somewhat non-obvious) behaviour that I'd forgotten about :-)

When you give a locale like `:en-US-var1` to Tempura, it auto-interprets (expands) into a descending-preference vector of locales like `[:en-US-var1 :en-US :en]`. That is: from most to least specific.

If a translation resource exists for `:en-US-var1`, that's the first choice.
Otherwise search `:en-US`.
Otherwise search `:en`.

So far so good.

What happens if you combine multiple locales to search like `[:en-US-var1 :fr-FR]`? That ends up expanding into an ordered search like `[:en-US-var1 :en-US :en :fr-FR :fr]`.

Again, so far so good.

Now what if we have a locale vector like `[:en-US-var1 :en-GB-var1]` or `[:en-US-var1 :fr-FR :en-GB]`? These appear to be well-formed, but actually contain subtle logical problems.

If we expand them, we get: `[:en-US-var1 :en-US :en :en-GB-var1 :en-GB :en]` and `[:en-US-var1 :en-US :en :fr-FR :fr :en-GB :en]`.

In both cases we have illogical searches like `:en` proceeding `:en-GB-var1`- a more general locale proceeding a less general one. But we want our search flow to proceed in the other direction: more specific to less specific, not more general to less general.

Now we _could_ adjust Tempura to just go to more effort when sorting the search tree- the problem is that we'd need a more complicated heuristic that's harder to understand/predict, and that'd inherently need to involve some arbitrary decisions about an ambiguous request.

Instead, Tempura tries to simplify this situation by just stating:
- Tempura ignores any preferences that seem to contradict earlier preferences
- Locale names actually convey semantic fallback structure: if you want a fallback for `:en-US`, the correct location is `:en`

I.e. in your case the suggested solution would be to restructure your dictionary so that `:en-*` fallbacks are placed in `:en`.

Does that help / seem reasonable?

**Closed as completed** 2017-03-24 17:36 UTC
Labels: can close?
